### ISSUE TITLE
API Token Visible on console log for incorrect Input 

### ISSUE THREAD

**Issue by rkgade** [gadeRaghav/Weather-API#1]
API TOKEN for incorrect entires is visible on console log.

Command 
`http://localhost:8080/weather/current?location=xyz`

Console Log 
`Error: java.io.FileNotFoundException: http://api.openweathermap.org/data/2.5/weather?q=xyz&appid=<API_TOKEN>`

**Comment by gade-raghav** [comment]
This Issue was also taken care of along with incorrect input issue. Once again Thank you for briniging this to our notice.
